# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 00:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rider', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={'NA': 'NA'})),
                ('soloRideHistory', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={'NA': 'NA'})),
            ],
        ),
    ]
