# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_riders_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='emailId',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='fcmToken',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='firstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='paymentPreference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='referralMoney',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='referredBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='walletId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
