# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_auto_20190628_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='phoneNumber',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
