# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_riders_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riders',
            new_name='Rider',
        ),
    ]
