# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_auto_20190628_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cancelTime', models.DateTimeField()),
                ('cancelType', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', django.contrib.postgres.fields.jsonb.JSONField()),
                ('destinationLocationEnglish', models.CharField(blank=True, max_length=255, null=True)),
                ('destinationLocationHindi', models.CharField(blank=True, max_length=255, null=True)),
                ('driverId', models.CharField(blank=True, max_length=255, null=True)),
                ('driverMobile', models.CharField(blank=True, max_length=255, null=True)),
                ('flushedDrivers', django.contrib.postgres.fields.hstore.HStoreField()),
                ('paymentMode', models.CharField(blank=True, max_length=255, null=True)),
                ('projectRideDistance', models.CharField(blank=True, max_length=255, null=True)),
                ('projectedPickupTime', models.CharField(blank=True, max_length=255, null=True)),
                ('projectRideCost', models.CharField(blank=True, max_length=255, null=True)),
                ('projectRideCostWithOffer', models.FloatField(blank=True, null=True)),
                ('projectedRideTime', models.CharField(blank=True, max_length=255, null=True)),
                ('requestedTime', models.DateField()),
                ('riderMobile', models.CharField(blank=True, max_length=255, null=True)),
                ('riderName', models.CharField(blank=True, max_length=255, null=True)),
                ('riderRating', models.CharField(blank=True, max_length=255, null=True)),
                ('source', django.contrib.postgres.fields.hstore.HStoreField()),
                ('sourceLocationEnglish', models.CharField(blank=True, max_length=255, null=True)),
                ('sourceLocationHindi', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[(b'Solo', b'Solo'), (b'Express', b'Express')], max_length=255, null=True)),
            ],
        ),
    ]
