# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_auto_20190628_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('aadharDocLink', models.CharField(blank=True, max_length=255, null=True)),
                ('adminCreditHistory', django.contrib.postgres.fields.hstore.HStoreField()),
                ('balanceAmmount', models.FloatField(blank=True, null=True)),
                ('banlAccName', models.CharField(blank=True, max_length=255, null=True)),
                ('cashRedeemPossible', models.BooleanField(default=False)),
                ('dOB', models.DateField(blank=True)),
                ('driverLevel', models.IntegerField(blank=True)),
                ('driverName', models.CharField(blank=True, max_length=255, null=True)),
                ('driverPicture', models.CharField(blank=True, max_length=255, null=True)),
                ('driverRaiting', models.FloatField(blank=True, null=True)),
                ('driverStatus', models.CharField(blank=True, choices=[(b'Idle', b'Idle'), (b'In a Ride', b'In a Ride')], max_length=255, null=True)),
                ('driverVerificationStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('erickshawNumber', models.IntegerField(blank=True, null=True)),
                ('fcmToken', models.CharField(blank=True, max_length=255, null=True)),
                ('ifscCode', models.CharField(blank=True, max_length=255, null=True)),
                ('lastKnownLocation', django.contrib.postgres.fields.hstore.HStoreField()),
                ('licenseDocLink', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('pendingAmount', models.FloatField(blank=True, null=True)),
                ('psvDocLink', models.CharField(blank=True, max_length=255, null=True)),
                ('redeemRequestHistory', django.contrib.postgres.fields.hstore.HStoreField()),
                ('referralMoney', models.CharField(blank=True, max_length=255, null=True)),
                ('referralTo', django.contrib.postgres.fields.hstore.HStoreField()),
                ('seats', django.contrib.postgres.fields.hstore.HStoreField()),
                ('soloExpressHistory', django.contrib.postgres.fields.hstore.HStoreField()),
                ('soloRideHistory', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
