# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 11:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='adminCreditHistory',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastKnownLocation',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='redeemRequestHistory',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='referralTo',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='seats',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='soloExpressHistory',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='soloRideHistory',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
    ]
