# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_auto_20190628_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
